[package]
name = "sandbox"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.102"
xenon-engine = { path = "../engine" }
pollster = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
softbuffer = "0.4.8"
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
winit = "0.30.13"
